apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy5
spec:
 completions: 5
 parallelism: 2
 template:
    spec:
      containers:
      - name: resting10
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
